# Generated by Django 5.2.4 on 2025-07-31 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام')),
                ('lastname', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/avatars/', verbose_name='آواتار')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about', verbose_name='پروفایل')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام اموزشگاه')),
                ('orientation', models.CharField(max_length=50, verbose_name='نام گرایش یا تخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع ')),
                ('end_date', models.DateField(default='Present', verbose_name='تاریخ پایان ')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about', verbose_name='پروفایل')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('company', models.CharField(max_length=50, verbose_name='نام شرکت یا سازمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع ')),
                ('end_date', models.DateField(default='Present', verbose_name='تاریخ پایان ')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about', verbose_name='پروفایل')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about', verbose_name='پروفایل')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('fab fa-node-js', 'Node.js'), ('fab fa-python', 'Python'), ('fas fa-database', 'Database'), ('fas fa-gamepad', 'Gamepad')], max_length=100, verbose_name='نام مهارت')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about', verbose_name='پروفایل')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialname', models.CharField(choices=[('fab fa-node-js', 'Node.js'), ('fab fa-python', 'Python'), ('fas fa-database', 'Database'), ('fas fa-gamepad', 'Gamepad')], max_length=100, verbose_name='نام شبکه اجتماعی')),
                ('socialurl', models.URLField(verbose_name='آدرس شبکه اجتماعی')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about', verbose_name='پروفایل')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='نام مهارت')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.about', verbose_name='پروفایل')),
            ],
        ),
    ]
