# Generated by Django 5.2.4 on 2025-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_about_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='معدل'),
        ),
    ]
