# Generated by Django 5.2.4 on 2025-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_education_gpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'verbose_name': 'دست آورد', 'verbose_name_plural': 'دست آورد ها'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'تحصیل', 'verbose_name_plural': 'تحصیلات'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'سابقه', 'verbose_name_plural': 'سوابق'},
        ),
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name': 'علاقه مندی', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'مهارت کاری', 'verbose_name_plural': 'مهارت های کاری'},
        ),
        migrations.AddField(
            model_name='about',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='about',
            name='address_fa',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='about',
            name='biography_en',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='about',
            name='biography_fa',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='about',
            name='firstname_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='about',
            name='firstname_fa',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='about',
            name='lastname_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='about',
            name='lastname_fa',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='awards',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='awards',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='education',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='education',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='education',
            name='orientation_en',
            field=models.CharField(max_length=50, null=True, verbose_name='نام گرایش یا تخصص'),
        ),
        migrations.AddField(
            model_name='education',
            name='orientation_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='نام گرایش یا تخصص'),
        ),
        migrations.AddField(
            model_name='education',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='نام اموزشگاه'),
        ),
        migrations.AddField(
            model_name='education',
            name='title_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='نام اموزشگاه'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=50, null=True, verbose_name='نام شرکت یا سازمان'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='نام شرکت یا سازمان'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='interests',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='interests',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='نام مهارت'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='title_fa',
            field=models.CharField(max_length=80, null=True, verbose_name='نام مهارت'),
        ),
    ]
